<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>netstandard2.1</TargetFramework>
        <RootNamespace>jwl.Wadl</RootNamespace>
		<ImplicitUsings>disable</ImplicitUsings>

        <AssemblyName>jwl.wadl</AssemblyName>
        <PackageId>NoP77svk.Jwl.Wadl</PackageId>
    </PropertyGroup>

</Project>
